# GitHub Actions workflow for deploying Python app to Azure Web App using Zip Deploy

name: Build and deploy Python app to Azure Web App - pqrsf-search-andje

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      # Set up Python environment
      - name: 'Set up Python version'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: 'Install Python dependencies'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Zip the application files for deployment
      - name: 'Zip artifact for deployment'
        run: |
          zip -r release.zip . -x "venv/*" "*.git/*" "*.github/*"

      # Deploy to Azure Web App using Zip Deploy
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pqrsf-search-andje'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3AE73103700D4AE6BDA06C218C97B33F }}
          package: './release.zip'
