# GitHub Actions workflow for deploying Python app to Azure Web App using Zip Deploy

name: Build and deploy Python app to Azure Web App - pqrsf-search-andje

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Zip the application files for deployment
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" "*.git/*" "*.github/*"

      # Upload the zip artifact for the deploy job
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download the zipped artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Deploy the application using Zip Deploy
      - name: 'Deploy to Azure Web App using Zip Deploy'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pqrsf-search-andje'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3AE73103700D4AE6BDA06C218C97B33F }}
          package: './release.zip'
          deploy-type: 'zip'  # Forzando el tipo de despliegue a Zip
